/* This code and any associated documentation is provided "as is"

Copyright 2024 Munich Quantum Software Stack Project

Licensed under the Apache License, Version 2.0 with LLVM Exceptions (the
"License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at

https://github.com/Munich-Quantum-Software-Stack/MQSS-Quantum-Compilation-Suite/blob/develop/LICENSE

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.

SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
*/

/** @file
 * @brief
 * @details Header file that defines the signature for each MLIR/Quake defined
 * into the Munich Quantum Software Stack (MQSS).
 *
 * @par
 * This header must be included to use the collection of transforms passes that
 * are part of the MQSS.
 */

#pragma once

#include "mlir/IR/BuiltinOps.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Pass/PassRegistry.h"

#include "llvm/Support/raw_ostream.h"

#include <stdexcept>

/**
 * @def GEN_PASS_REGISTRATION
 * @brief Macro for pass registration
 */

#define GEN_PASS_DECL
#include "Passes/Transforms/TransformPasses.h.inc"

/**
 * @def CUDAQ_PREFIX_FUNCTION
 * @brief Macro defining the prefix of each quantum kernel generated by
 * MLIR/Quake. This macro is used to identify MLIR/Quake quantum kernels.
 */
#define CUDAQ_PREFIX_FUNCTION "__nvqpp__mlirgen__"

namespace mqss::mqssci::opt {

// Gate Pattern Cancellation passes
std::unique_ptr<mlir::Pass> CommonGateCancellationPass();
std::unique_ptr<mlir::Pass> CommonCommutePass();
std::unique_ptr<mlir::Pass> CommonDecompositionPass();
std::unique_ptr<mlir::Pass> CommonNormalizeArgAnglePass();
// Gate Pattern Switch passes

std::unique_ptr<mlir::Pass> CommonSwitchPass();
std::unique_ptr<mlir::Pass> CommonReductionPass();
std::unique_ptr<mlir::Pass> CommonCNOTReversePass();
std::unique_ptr<mlir::Pass> CommonMappingPass();

// Programmatic Pass Registration
std::unique_ptr<mlir::Pass>
CommonCommutePass(const CommonCommutePassOptions &options);

std::unique_ptr<mlir::Pass>
CommonGateCancellationPass(const CommonGateCancellationPassOptions &options);

std::unique_ptr<mlir::Pass>
CommonSwitchPass(const CommonSwitchPassOptions &options);

std::unique_ptr<mlir::Pass>
CommonDecompositionPass(const CommonDecompositionPassOptions &options);

std::unique_ptr<mlir::Pass>
CommonReductionPass(const CommonReductionPassOptions &options);

std::unique_ptr<mlir::Pass> CommonMappingPass(
    const std::vector<std::pair<std::uint32_t, std::uint32_t>> &coupling_map);
std::unique_ptr<mlir::Pass>
CommonMappingPass(const CommonMappingPassOptions &options);

} // namespace mqss::mqssci::opt

#define GEN_PASS_REGISTRATION
#include "Passes/Transforms/TransformPasses.h.inc"
