/* This code and any associated documentation is provided "as is"

Copyright 2024 Munich Quantum Software Stack Project

Licensed under the Apache License, Version 2.0 with LLVM Exceptions (the
"License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at

https://github.com/Munich-Quantum-Software-Stack/MQSS-Quantum-Compilation-Suite/blob/develop/LICENSE

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.

SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
*/

include "mlir/Pass/PassBase.td"


def CommonCircuitVerificationPass : Pass<"CommonCircuitVerificationPass", "mlir::ModuleOp"> {
  let summary = "Verifies if two circuits are equivalent";

  let description = [{
        This pass verifies if two circuits are equivalent using the mqt-qcec library.
        The pass can be used to verify the correctness of the transformations performed by the passes in this library.
  }];

  let constructor = "mqss::mqssci::verify::CommonCircuitVerificationPass()";
}
